#   conda env create -f environment.yml
#   conda activate stcluster

name: stcluster

channels:
  - conda-forge

dependencies:
  - python==3.10
  - scanpy==1.9.3
  - squidpy
  - scikit-misc
  - louvain
  - openpyxl
  - anndata==0.10.8
  - rpy2<3.5.0
  - r-base
  - r-mclust
  - setuptools=80.9.0
  - pytorch==1.13.1
  - pip
  - pip:
      - dgl==1.1.1
