# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Gradient (Internal C++ function)
#'
#' @param X Numeric Matrix
#' @param D_x Numeric Matrix
#' @param a Numeric Matrix
#' @param b Numeric Matrix
#' @param eps Double
#' @return Gradient matrix
compute_grad <- function(X, D_x, a, b, eps = 1e-20) {
    .Call(`_DOST_compute_grad`, X, D_x, a, b, eps)
}

